/*
 * 文件作用：
 * 这个脚本负责把 src/main.js 入口开始的 ESM 源码打包成 dist/main.js。
 *
 * 执行逻辑：
 * 1. npm run build:js 会调用本文件。
 * 2. esbuild 从 src/main.js 出发，沿着 import 链把 src/plugin、src/renderer、src/parser 等模块打进一个文件。
 * 3. obsidian 被标记为 external，因为它不是 npm 依赖，而是 Obsidian 运行时提供的宿主 API。
 * 4. 输出格式仍然是 cjs，目的是让 Obsidian/Electron 以传统插件入口方式稳定加载 main.js。
 * 5. 输出目录使用 dist/，让开发源码和发布产物分开。
 *
 * 调用链位置：
 * package.json scripts.build:js -> scripts/build-js.mjs -> esbuild -> dist/main.js
 */

import * as esbuild from 'esbuild';
import fs from 'node:fs';

// build:js 可以单独执行，所以这里先确保 dist/ 已创建。
fs.mkdirSync('dist', { recursive: true });

await esbuild.build({
  // src/main.js 是源码层入口，所有业务模块都会从这个入口被 esbuild 追踪进 bundle。
  entryPoints: ['src/main.js'],
  bundle: true,
  platform: 'node',
  // Obsidian 插件入口保持 CommonJS，避免运行时把 main.js 当成 ESM 解析。
  format: 'cjs',
  // obsidian 由宿主应用提供，不应该被打进插件包。
  external: ['obsidian'],
  outfile: 'dist/main.js',
  banner: {
    js: [
      '/*',
      ' * Generated by scripts/build-js.mjs from src/main.js.',
      ' * Edit files in src/ instead of editing this file directly.',
      ' */',
    ].join('\n'),
  },
  logLevel: 'info',
});
