/*
 * 文件作用：
 * 这个脚本负责把 styles/index.css 里声明的 CSS 分层文件合并成 dist/styles.css。
 *
 * 执行逻辑：
 * 1. npm run build:css 会调用本文件。
 * 2. readCssWithImports 从 styles/index.css 开始读取 @import。
 * 3. 每遇到一个相对路径 import，就递归读取对应 CSS 文件并拼接内容。
 * 4. 最终写出 dist/styles.css，供发布目录和 Obsidian 插件安装目录加载。
 *
 * 调用链位置：
 * package.json scripts.build:css -> scripts/build-css.mjs -> styles/index.css -> dist/styles.css
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const entryFile = path.join(projectRoot, 'styles', 'index.css');
const outputFile = path.join(projectRoot, 'dist', 'styles.css');

function readCssWithImports(filePath, seen = new Set()) {
  const normalizedPath = path.normalize(filePath);
  if (seen.has(normalizedPath)) {
    return '';
  }
  seen.add(normalizedPath);

  const content = fs.readFileSync(normalizedPath, 'utf8');
  const currentDir = path.dirname(normalizedPath);
  const lines = content.split(/\r?\n/);
  const chunks = [];

  for (const line of lines) {
    const importMatch = line.match(/^@import\s+['"](.+)['"];\s*$/);
    if (!importMatch) {
      chunks.push(line);
      continue;
    }

    const importedFile = path.resolve(currentDir, importMatch[1]);
    chunks.push(readCssWithImports(importedFile, seen).trimEnd());
  }

  return chunks.join('\n');
}

const banner = [
  '/*',
  ' * Generated by scripts/build-css.mjs from styles/index.css.',
  ' * Edit files in styles/ instead of editing this file directly.',
  ' */',
  '',
].join('\n');

const output = `${banner}${readCssWithImports(entryFile).trim()}\n`;
fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, output);
